# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:year/:month/:day/:title.html

include:     	  ['.htaccess']

timezone:  		  Asia/Shanghai
lsi:			  true


# Permalinks
permalink:        pretty

# Setup
title:            BoLau
tagline:          '作记录的地方'
description:      '<a href="http://weibo.com/liuihc" target="_blank">BoLau</a><br/>用来记录胡思乱想的地方 '
url:              http://weibo.com/liuihc
baseurl:          '/'
paginate:         2

author:
  name:           'BoLau'
  url:            http://weibo.com/liuihc

# Custom vars
version:          1.0.0

github:
  repo:           http://weibo.com/liuihc

pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
