# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            BoLau
tagline:          '作记录的地方'
description:      '<a href="http://liuihc.github.io" target="_blank">BoLau</a>用来记录胡思乱想的地方 '
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
